image: beda42/validation-tool-ci:02

stages:
  - lints
  - tests
  - build

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - .venv/

include:
  - local: /.gitlab/pre-commit.yml
  - local: /.gitlab/run-tests.yml
  - local: /.gitlab/build-vue.yml
